### ISSUE TITLE
train_multi_gpu_using_spawn

### ISSUE THREAD

**Issue by Nireil** [WZMIAOMIAO/deep-learning-for-image-processing#560]
作者您好，我按照您的train_multi_gpu_using_spawn.py 写了一个自己的多卡训练程序，执行到p.start()时，torch.cuda.is_available()返回false，但在执行这一段程序前，torch.cuda.is_available()返回的是true呀，请问您知道是怎么回事吗

**Comment by WZMIAOMIAO** [comment]
不太清楚哦，自己写的代码自己找找问题吧。

**Comment by Nireil** [comment]
这个问题我已经解决了，spawn启动的话，需要在代码里添加torch.multiprocessing.start_method('spawn')
